// Generated by scripts/gen-types.mjs. Do not edit by hand; run `npm run db:types`.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_log: {
        Row: {
          id: number;
          actor_id: string | null;
          actor_role: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          before: Json | null;
          after: Json | null;
          ip: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          actor_role?: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          actor_role?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "audit_log_actor_id_fkey"; columns: ["actor_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      availability_windows: {
        Row: {
          id: string;
          listing_id: string;
          start_date: string;
          end_date: string;
          nightly_rate_cents: number;
          cleaning_fee_cents: number;
          min_nights: number;
          max_nights: number | null;
          whole_window_only: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          start_date: string;
          end_date: string;
          nightly_rate_cents: number;
          cleaning_fee_cents?: number;
          min_nights?: number;
          max_nights?: number | null;
          whole_window_only?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          start_date?: string;
          end_date?: string;
          nightly_rate_cents?: number;
          cleaning_fee_cents?: number;
          min_nights?: number;
          max_nights?: number | null;
          whole_window_only?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "availability_windows_listing_id_fkey"; columns: ["listing_id"]; isOneToOne: false; referencedRelation: "listings"; referencedColumns: ["id"] }
        ];
      };
      booking_events: {
        Row: {
          id: number;
          booking_id: string;
          from_status: Database["public"]["Enums"]["booking_status"] | null;
          to_status: Database["public"]["Enums"]["booking_status"];
          actor_id: string | null;
          note: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: number;
          booking_id: string;
          from_status?: Database["public"]["Enums"]["booking_status"] | null;
          to_status: Database["public"]["Enums"]["booking_status"];
          actor_id?: string | null;
          note?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          booking_id?: string;
          from_status?: Database["public"]["Enums"]["booking_status"] | null;
          to_status?: Database["public"]["Enums"]["booking_status"];
          actor_id?: string | null;
          note?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "booking_events_actor_id_fkey"; columns: ["actor_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "booking_events_booking_id_fkey"; columns: ["booking_id"]; isOneToOne: false; referencedRelation: "bookings"; referencedColumns: ["id"] }
        ];
      };
      bookings: {
        Row: {
          id: string;
          listing_id: string;
          availability_window_id: string | null;
          owner_id: string;
          renter_id: string;
          check_in: string;
          check_out: string;
          stay: string | null;
          nights: number | null;
          guests: number;
          status: Database["public"]["Enums"]["booking_status"];
          currency: string;
          nightly_rate_cents: number;
          cleaning_fee_cents: number;
          subtotal_cents: number;
          renter_total_cents: number;
          platform_fee_bps: number;
          platform_fee_cents: number;
          owner_payout_cents: number;
          cancellation_policy: Database["public"]["Enums"]["cancellation_policy"];
          stripe_payment_intent_id: string | null;
          stripe_payment_method_id: string | null;
          request_expires_at: string;
          hold_expires_at: string | null;
          accepted_at: string | null;
          confirmed_at: string | null;
          declined_at: string | null;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          checked_in_at: string | null;
          completed_at: string | null;
          renter_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          availability_window_id?: string | null;
          owner_id: string;
          renter_id: string;
          check_in: string;
          check_out: string;
          guests?: number;
          status?: Database["public"]["Enums"]["booking_status"];
          currency?: string;
          nightly_rate_cents: number;
          cleaning_fee_cents?: number;
          subtotal_cents: number;
          renter_total_cents: number;
          platform_fee_bps: number;
          platform_fee_cents: number;
          owner_payout_cents: number;
          cancellation_policy: Database["public"]["Enums"]["cancellation_policy"];
          stripe_payment_intent_id?: string | null;
          stripe_payment_method_id?: string | null;
          request_expires_at: string;
          hold_expires_at?: string | null;
          accepted_at?: string | null;
          confirmed_at?: string | null;
          declined_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          checked_in_at?: string | null;
          completed_at?: string | null;
          renter_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          availability_window_id?: string | null;
          owner_id?: string;
          renter_id?: string;
          check_in?: string;
          check_out?: string;
          guests?: number;
          status?: Database["public"]["Enums"]["booking_status"];
          currency?: string;
          nightly_rate_cents?: number;
          cleaning_fee_cents?: number;
          subtotal_cents?: number;
          renter_total_cents?: number;
          platform_fee_bps?: number;
          platform_fee_cents?: number;
          owner_payout_cents?: number;
          cancellation_policy?: Database["public"]["Enums"]["cancellation_policy"];
          stripe_payment_intent_id?: string | null;
          stripe_payment_method_id?: string | null;
          request_expires_at?: string;
          hold_expires_at?: string | null;
          accepted_at?: string | null;
          confirmed_at?: string | null;
          declined_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          checked_in_at?: string | null;
          completed_at?: string | null;
          renter_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "bookings_availability_window_id_fkey"; columns: ["availability_window_id"]; isOneToOne: false; referencedRelation: "availability_windows"; referencedColumns: ["id"] },
          { foreignKeyName: "bookings_listing_id_fkey"; columns: ["listing_id"]; isOneToOne: false; referencedRelation: "listings"; referencedColumns: ["id"] },
          { foreignKeyName: "bookings_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "bookings_renter_id_fkey"; columns: ["renter_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      conversations: {
        Row: {
          id: string;
          booking_id: string;
          owner_id: string;
          renter_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          owner_id: string;
          renter_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          owner_id?: string;
          renter_id?: string;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "conversations_booking_id_fkey"; columns: ["booking_id"]; isOneToOne: true; referencedRelation: "bookings"; referencedColumns: ["id"] },
          { foreignKeyName: "conversations_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "conversations_renter_id_fkey"; columns: ["renter_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      ledger_entries: {
        Row: {
          id: number;
          booking_id: string | null;
          user_id: string | null;
          kind: Database["public"]["Enums"]["ledger_kind"];
          amount_cents: number;
          currency: string;
          stripe_object_id: string | null;
          stripe_event_id: string | null;
          memo: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          booking_id?: string | null;
          user_id?: string | null;
          kind: Database["public"]["Enums"]["ledger_kind"];
          amount_cents: number;
          currency?: string;
          stripe_object_id?: string | null;
          stripe_event_id?: string | null;
          memo?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          booking_id?: string | null;
          user_id?: string | null;
          kind?: Database["public"]["Enums"]["ledger_kind"];
          amount_cents?: number;
          currency?: string;
          stripe_object_id?: string | null;
          stripe_event_id?: string | null;
          memo?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "ledger_entries_booking_id_fkey"; columns: ["booking_id"]; isOneToOne: false; referencedRelation: "bookings"; referencedColumns: ["id"] },
          { foreignKeyName: "ledger_entries_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      listing_photos: {
        Row: {
          id: string;
          listing_id: string;
          storage_path: string;
          caption: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          storage_path: string;
          caption?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          storage_path?: string;
          caption?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "listing_photos_listing_id_fkey"; columns: ["listing_id"]; isOneToOne: false; referencedRelation: "listings"; referencedColumns: ["id"] }
        ];
      };
      listings: {
        Row: {
          id: string;
          owner_id: string;
          resort_id: string;
          title: string;
          description: string | null;
          unit_type: Database["public"]["Enums"]["unit_type"];
          bedrooms: number;
          bathrooms: number;
          sleeps: number;
          amenities: string[];
          house_rules: string | null;
          cancellation_policy: Database["public"]["Enums"]["cancellation_policy"];
          status: Database["public"]["Enums"]["listing_status"];
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          resort_id: string;
          title: string;
          description?: string | null;
          unit_type: Database["public"]["Enums"]["unit_type"];
          bedrooms?: number;
          bathrooms?: number;
          sleeps: number;
          amenities?: string[];
          house_rules?: string | null;
          cancellation_policy?: Database["public"]["Enums"]["cancellation_policy"];
          status?: Database["public"]["Enums"]["listing_status"];
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          resort_id?: string;
          title?: string;
          description?: string | null;
          unit_type?: Database["public"]["Enums"]["unit_type"];
          bedrooms?: number;
          bathrooms?: number;
          sleeps?: number;
          amenities?: string[];
          house_rules?: string | null;
          cancellation_policy?: Database["public"]["Enums"]["cancellation_policy"];
          status?: Database["public"]["Enums"]["listing_status"];
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "listings_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "listings_resort_id_fkey"; columns: ["resort_id"]; isOneToOne: false; referencedRelation: "resorts"; referencedColumns: ["id"] }
        ];
      };
      messages: {
        Row: {
          id: number;
          conversation_id: string;
          sender_id: string;
          body: string;
          created_at: string;
          read_at: string | null;
        };
        Insert: {
          id?: number;
          conversation_id: string;
          sender_id: string;
          body: string;
          created_at?: string;
          read_at?: string | null;
        };
        Update: {
          id?: number;
          conversation_id?: string;
          sender_id?: string;
          body?: string;
          created_at?: string;
          read_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "messages_conversation_id_fkey"; columns: ["conversation_id"]; isOneToOne: false; referencedRelation: "conversations"; referencedColumns: ["id"] },
          { foreignKeyName: "messages_sender_id_fkey"; columns: ["sender_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      notifications: {
        Row: {
          id: number;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          data: Json;
          channels: Database["public"]["Enums"]["notification_channel"][];
          read_at: string | null;
          emailed_at: string | null;
          email_provider_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          data?: Json;
          channels?: Database["public"]["Enums"]["notification_channel"][];
          read_at?: string | null;
          emailed_at?: string | null;
          email_provider_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string | null;
          data?: Json;
          channels?: Database["public"]["Enums"]["notification_channel"][];
          read_at?: string | null;
          emailed_at?: string | null;
          email_provider_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "notifications_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      owner_verifications: {
        Row: {
          id: string;
          owner_id: string;
          ownership_doc_path: string | null;
          ownership_doc_type: string | null;
          resort_id: string | null;
          ownership_doc_uploaded_at: string | null;
          stripe_identity_session_id: string | null;
          identity_status: Database["public"]["Enums"]["identity_status"];
          identity_verified_at: string | null;
          status: Database["public"]["Enums"]["owner_verification_status"];
          submitted_at: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          ownership_doc_path?: string | null;
          ownership_doc_type?: string | null;
          resort_id?: string | null;
          ownership_doc_uploaded_at?: string | null;
          stripe_identity_session_id?: string | null;
          identity_status?: Database["public"]["Enums"]["identity_status"];
          identity_verified_at?: string | null;
          status?: Database["public"]["Enums"]["owner_verification_status"];
          submitted_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          ownership_doc_path?: string | null;
          ownership_doc_type?: string | null;
          resort_id?: string | null;
          ownership_doc_uploaded_at?: string | null;
          stripe_identity_session_id?: string | null;
          identity_status?: Database["public"]["Enums"]["identity_status"];
          identity_verified_at?: string | null;
          status?: Database["public"]["Enums"]["owner_verification_status"];
          submitted_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "owner_verifications_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "owner_verifications_resort_id_fkey"; columns: ["resort_id"]; isOneToOne: false; referencedRelation: "resorts"; referencedColumns: ["id"] },
          { foreignKeyName: "owner_verifications_reviewed_by_fkey"; columns: ["reviewed_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      payments: {
        Row: {
          id: string;
          booking_id: string;
          renter_id: string;
          stripe_payment_intent_id: string;
          stripe_charge_id: string | null;
          stripe_customer_id: string | null;
          amount_cents: number;
          amount_refunded_cents: number;
          currency: string;
          status: Database["public"]["Enums"]["payment_status"];
          failure_code: string | null;
          failure_message: string | null;
          stripe_fee_cents: number | null;
          succeeded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          renter_id: string;
          stripe_payment_intent_id: string;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          amount_cents: number;
          amount_refunded_cents?: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          failure_code?: string | null;
          failure_message?: string | null;
          stripe_fee_cents?: number | null;
          succeeded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          renter_id?: string;
          stripe_payment_intent_id?: string;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          amount_cents?: number;
          amount_refunded_cents?: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          failure_code?: string | null;
          failure_message?: string | null;
          stripe_fee_cents?: number | null;
          succeeded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "payments_booking_id_fkey"; columns: ["booking_id"]; isOneToOne: false; referencedRelation: "bookings"; referencedColumns: ["id"] },
          { foreignKeyName: "payments_renter_id_fkey"; columns: ["renter_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      payouts: {
        Row: {
          id: string;
          booking_id: string;
          owner_id: string;
          stripe_account_id: string | null;
          amount_cents: number;
          currency: string;
          status: Database["public"]["Enums"]["payout_status"];
          stripe_transfer_id: string | null;
          stripe_transfer_reversal_id: string | null;
          releasable_at: string | null;
          released_at: string | null;
          reversed_at: string | null;
          blocked_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          owner_id: string;
          stripe_account_id?: string | null;
          amount_cents: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payout_status"];
          stripe_transfer_id?: string | null;
          stripe_transfer_reversal_id?: string | null;
          releasable_at?: string | null;
          released_at?: string | null;
          reversed_at?: string | null;
          blocked_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          owner_id?: string;
          stripe_account_id?: string | null;
          amount_cents?: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payout_status"];
          stripe_transfer_id?: string | null;
          stripe_transfer_reversal_id?: string | null;
          releasable_at?: string | null;
          released_at?: string | null;
          reversed_at?: string | null;
          blocked_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "payouts_booking_id_fkey"; columns: ["booking_id"]; isOneToOne: true; referencedRelation: "bookings"; referencedColumns: ["id"] },
          { foreignKeyName: "payouts_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      platform_settings: {
        Row: {
          id: boolean;
          platform_fee_bps: number;
          request_ttl: string;
          checkout_hold_ttl: string;
          payout_release_delay: string;
          currency: string;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          platform_fee_bps?: number;
          request_ttl?: string;
          checkout_hold_ttl?: string;
          payout_release_delay?: string;
          currency?: string;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          platform_fee_bps?: number;
          request_ttl?: string;
          checkout_hold_ttl?: string;
          payout_release_delay?: string;
          currency?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          avatar_path: string | null;
          owner_verification_status: Database["public"]["Enums"]["owner_verification_status"];
          stripe_customer_id: string | null;
          us_state: string | null;
          terms_accepted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_path?: string | null;
          owner_verification_status?: Database["public"]["Enums"]["owner_verification_status"];
          stripe_customer_id?: string | null;
          us_state?: string | null;
          terms_accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_path?: string | null;
          owner_verification_status?: Database["public"]["Enums"]["owner_verification_status"];
          stripe_customer_id?: string | null;
          us_state?: string | null;
          terms_accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "profiles_id_fkey"; columns: ["id"]; isOneToOne: true; referencedRelation: "auth.users"; referencedColumns: ["id"] }
        ];
      };
      refunds: {
        Row: {
          id: string;
          booking_id: string;
          payment_id: string;
          stripe_refund_id: string | null;
          amount_cents: number;
          currency: string;
          reason: string;
          status: Database["public"]["Enums"]["refund_status"];
          initiated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          payment_id: string;
          stripe_refund_id?: string | null;
          amount_cents: number;
          currency?: string;
          reason: string;
          status?: Database["public"]["Enums"]["refund_status"];
          initiated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          payment_id?: string;
          stripe_refund_id?: string | null;
          amount_cents?: number;
          currency?: string;
          reason?: string;
          status?: Database["public"]["Enums"]["refund_status"];
          initiated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "refunds_booking_id_fkey"; columns: ["booking_id"]; isOneToOne: false; referencedRelation: "bookings"; referencedColumns: ["id"] },
          { foreignKeyName: "refunds_initiated_by_fkey"; columns: ["initiated_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "refunds_payment_id_fkey"; columns: ["payment_id"]; isOneToOne: false; referencedRelation: "payments"; referencedColumns: ["id"] }
        ];
      };
      resort_confirmations: {
        Row: {
          id: string;
          booking_id: string;
          owner_id: string;
          storage_path: string | null;
          confirmation_number: string | null;
          guest_name_on_reservation: string | null;
          status: Database["public"]["Enums"]["confirmation_status"];
          submitted_at: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          owner_id: string;
          storage_path?: string | null;
          confirmation_number?: string | null;
          guest_name_on_reservation?: string | null;
          status?: Database["public"]["Enums"]["confirmation_status"];
          submitted_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          owner_id?: string;
          storage_path?: string | null;
          confirmation_number?: string | null;
          guest_name_on_reservation?: string | null;
          status?: Database["public"]["Enums"]["confirmation_status"];
          submitted_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "resort_confirmations_booking_id_fkey"; columns: ["booking_id"]; isOneToOne: true; referencedRelation: "bookings"; referencedColumns: ["id"] },
          { foreignKeyName: "resort_confirmations_owner_id_fkey"; columns: ["owner_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "resort_confirmations_reviewed_by_fkey"; columns: ["reviewed_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      resorts: {
        Row: {
          id: string;
          name: string;
          brand: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string;
          state: string;
          postal_code: string | null;
          country: string;
          latitude: number | null;
          longitude: number | null;
          timezone: string;
          website_url: string | null;
          is_verified: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          brand?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city: string;
          state: string;
          postal_code?: string | null;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string;
          website_url?: string | null;
          is_verified?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          brand?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string;
          state?: string;
          postal_code?: string | null;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string;
          website_url?: string | null;
          is_verified?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "resorts_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      stripe_accounts: {
        Row: {
          user_id: string;
          stripe_account_id: string;
          charges_enabled: boolean;
          payouts_enabled: boolean;
          details_submitted: boolean;
          requirements: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          stripe_account_id: string;
          charges_enabled?: boolean;
          payouts_enabled?: boolean;
          details_submitted?: boolean;
          requirements?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          stripe_account_id?: string;
          charges_enabled?: boolean;
          payouts_enabled?: boolean;
          details_submitted?: boolean;
          requirements?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "stripe_accounts_user_id_fkey"; columns: ["user_id"]; isOneToOne: true; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      stripe_events: {
        Row: {
          id: string;
          type: string;
          account_id: string | null;
          payload: Json;
          received_at: string;
          processed_at: string | null;
          error: string | null;
        };
        Insert: {
          id: string;
          type: string;
          account_id?: string | null;
          payload: Json;
          received_at?: string;
          processed_at?: string | null;
          error?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          account_id?: string | null;
          payload?: Json;
          received_at?: string;
          processed_at?: string | null;
          error?: string | null;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by: string | null;
          granted_at: string;
        };
        Insert: {
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          granted_at?: string;
        };
        Update: {
          user_id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          granted_at?: string;
        };
        Relationships: [
          { foreignKeyName: "user_roles_granted_by_fkey"; columns: ["granted_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "user_roles_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
    };
    Views: {
      public_profiles: {
        Row: {
          id: string | null;
          full_name: string | null;
          avatar_path: string | null;
          owner_verification_status: Database["public"]["Enums"]["owner_verification_status"] | null;
          created_at: string | null;
        };
        Relationships: [];
      };
      releasable_payouts: {
        Row: {
          id: string | null;
          booking_id: string | null;
          owner_id: string | null;
          stripe_account_id: string | null;
          amount_cents: number | null;
          currency: string | null;
          status: Database["public"]["Enums"]["payout_status"] | null;
          stripe_transfer_id: string | null;
          stripe_transfer_reversal_id: string | null;
          releasable_at: string | null;
          released_at: string | null;
          reversed_at: string | null;
          blocked_reason: string | null;
          created_at: string | null;
          updated_at: string | null;
          live_stripe_account_id: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      accept_booking: { Args: { p_booking_id: string }; Returns: Database["public"]["Tables"]["bookings"]["Row"] };
      advance_stays: { Args: Record<PropertyKey, never>; Returns: undefined };
      become_owner: { Args: Record<PropertyKey, never>; Returns: undefined };
      block_payout: { Args: { p_payout_id: string; p_reason: string }; Returns: Database["public"]["Tables"]["payouts"]["Row"] };
      cancel_booking: { Args: { p_booking_id: string; p_reason?: string }; Returns: Database["public"]["Tables"]["bookings"]["Row"] };
      custom_access_token_hook: { Args: { event: Json }; Returns: Json };
      decline_booking: { Args: { p_booking_id: string; p_reason?: string }; Returns: Database["public"]["Tables"]["bookings"]["Row"] };
      expire_stale_bookings: { Args: Record<PropertyKey, never>; Returns: unknown[] };
      grant_role: { Args: { p_user_id: string; p_role: Database["public"]["Enums"]["app_role"] }; Returns: undefined };
      has_role: { Args: { p_role: Database["public"]["Enums"]["app_role"] }; Returns: boolean };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_service_role: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_verified_owner: { Args: Record<PropertyKey, never>; Returns: boolean };
      mark_booking_confirmed: { Args: { p_booking_id: string; p_payment_intent_id: string }; Returns: Database["public"]["Tables"]["bookings"]["Row"] };
      mark_booking_payment_failed: { Args: { p_booking_id: string; p_reason?: string }; Returns: Database["public"]["Tables"]["bookings"]["Row"] };
      mark_payout_released: { Args: { p_payout_id: string; p_transfer_id: string }; Returns: Database["public"]["Tables"]["payouts"]["Row"] };
      mark_payouts_releasable: { Args: Record<PropertyKey, never>; Returns: Database["public"]["Tables"]["payouts"]["Row"][] };
      quote_stay: { Args: { p_window_id: string; p_check_in: string; p_check_out: string }; Returns: PriceQuote };
      request_booking: { Args: { p_window_id: string; p_check_in: string; p_check_out: string; p_guests: number; p_payment_method_id: string; p_note?: string }; Returns: Database["public"]["Tables"]["bookings"]["Row"] };
      review_owner_verification: { Args: { p_verification_id: string; p_approve: boolean; p_reason?: string }; Returns: Database["public"]["Tables"]["owner_verifications"]["Row"] };
      review_resort_confirmation: { Args: { p_booking_id: string; p_approve: boolean; p_reason?: string }; Returns: Database["public"]["Tables"]["resort_confirmations"]["Row"] };
      revoke_role: { Args: { p_user_id: string; p_role: Database["public"]["Enums"]["app_role"] }; Returns: undefined };
      submit_owner_verification: { Args: { p_verification_id: string }; Returns: Database["public"]["Tables"]["owner_verifications"]["Row"] };
      submit_resort_confirmation: { Args: { p_booking_id: string; p_storage_path: string; p_confirmation_number: string; p_guest_name: string }; Returns: Database["public"]["Tables"]["resort_confirmations"]["Row"] };
    };
    Enums: {
      app_role: "renter" | "owner" | "admin";
      booking_status: "requested" | "accepting" | "payment_failed" | "confirmed" | "declined" | "expired" | "cancelled_by_renter" | "cancelled_by_owner" | "cancelled_by_admin" | "checked_in" | "completed" | "disputed";
      cancellation_policy: "flexible" | "moderate" | "strict" | "non_refundable";
      confirmation_status: "missing" | "submitted" | "approved" | "rejected";
      identity_status: "not_started" | "requires_input" | "processing" | "verified" | "canceled";
      ledger_kind: "charge" | "platform_fee" | "transfer" | "transfer_reversal" | "refund" | "dispute" | "dispute_reversal" | "adjustment";
      listing_status: "draft" | "active" | "paused" | "archived" | "removed_by_admin";
      notification_channel: "in_app" | "email" | "push";
      owner_verification_status: "not_started" | "in_progress" | "pending_review" | "approved" | "rejected";
      payment_status: "requires_action" | "processing" | "succeeded" | "failed" | "canceled" | "refunded" | "partially_refunded";
      payout_status: "held" | "releasable" | "released" | "reversed" | "blocked";
      refund_status: "pending" | "succeeded" | "failed" | "canceled";
      unit_type: "studio" | "1br" | "2br" | "3br" | "4br" | "lockoff" | "other";
    };
    CompositeTypes: {
      price_quote: PriceQuote;
    };
  };
};

export type PriceQuote = {
  nights: number;
  nightly_rate_cents: number;
  cleaning_fee_cents: number;
  subtotal_cents: number;
  renter_total_cents: number;
  platform_fee_bps: number;
  platform_fee_cents: number;
  owner_payout_cents: number;
};

// Convenience aliases
export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T];
export type AppRole = Enums<"app_role">;
export type BookingStatus = Enums<"booking_status">;
export type CancellationPolicy = Enums<"cancellation_policy">;
export type ConfirmationStatus = Enums<"confirmation_status">;
export type IdentityStatus = Enums<"identity_status">;
export type LedgerKind = Enums<"ledger_kind">;
export type ListingStatus = Enums<"listing_status">;
export type NotificationChannel = Enums<"notification_channel">;
export type OwnerVerificationStatus = Enums<"owner_verification_status">;
export type PaymentStatus = Enums<"payment_status">;
export type PayoutStatus = Enums<"payout_status">;
export type RefundStatus = Enums<"refund_status">;
export type UnitType = Enums<"unit_type">;
export type Profile = Tables<"profiles">;
export type UserRole = Tables<"user_roles">;
export type Listing = Tables<"listings">;
export type Resort = Tables<"resorts">;
export interface AppClaims { app_roles?: AppRole[]; owner_status?: OwnerVerificationStatus }
